name: proklinik_one
description: "proclinic migration to proklinik doctor portal - fully fledged online clinic management system - doctor port"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  pdf: ^3.11.1
  uuid: ^4.5.0
  pocketbase: ^0.23.0
  intl: ^0.20.2
  http: ^1.2.2
  http_parser: ^4.0.2
  printing: ^5.13.2
  file_picker: ^10.2.0
  go_router: ^15.2.0
  equatable: ^2.0.5
  email_validator: ^3.0.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/fonts/IBM/
    - assets/lang/
    - assets/json/

  fonts:
    - family: IBM
      fonts:
        - asset: assets/fonts/IBM/font-Thin-100.ttf
          style: normal
          weight: 100
        - asset: assets/fonts/IBM/font-ExtraLight-200.ttf
          style: normal
          weight: 200
        - asset: assets/fonts/IBM/font-Light-300.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/IBM/font-Regular-400.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/IBM/font-Medium-500.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/IBM/font-SemiBold-600.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/IBM/font-Bold-700.ttf
          style: normal
          weight: 700
