enum BookkeepingName {
  visit_create,
  visit_no_update,
  //visit_attendance
  visit_attendance_update_attended,
  visit_attendance_update_not_attended,
  //visit_type
  visit_type_update,
  visit_type_update_consultation,
  visit_type_update_followup,
  visit_type_update_procedure,
  //visit_procedures
  visit_procedure_add,
  visit_procedure_remove,
  //visit_supplies
  visit_supplies_add,
  visit_supplies_remove,
  visit_supplies_no_update,
  //supplies
  supplies_movement_add_manual,
  supplies_movement_remove_manual,
  supplies_movement_no_update_manual,
}
